export const songs = [
    {
        name: 'All The Same',
        artist: 'Deerhunter',
        album: 'Fading Frontier',
        uri: 'https://open.spotify.com/intl-de/track/00nGe8oBbXREOudq1e4gbu?si=45f6f5e0047b48a6',
    },
    {
        name: 'All The Same',
        artist: 'Does It Offend You, Yeah?',
        album: 'All The Same',
        uri: 'https://open.spotify.com/intl-de/track/62MYN20MuINHKPS9tw1E9U?si=05a73b4e84d44e05',
    },
    {
        name: 'All The Same',
        artist: 'Real Estate',
        album: 'Days',
        uri: 'https://open.spotify.com/intl-de/track/2YYmmCXYecSSC0d7CPBTiE?si=0a0e0eda33244848',
    },
    {
        name: 'All The Same',
        artist: 'The Voidz',
        album: 'Like All Before You',
        uri: 'https://open.spotify.com/intl-de/track/0omq85l4CACh9M3VLo0syk?si=1ebfaf2da34842c5',
    },
    {
        name: 'All The Same',
        artist: 'Wavves',
        album: 'V',
        uri: 'https://open.spotify.com/intl-de/track/2DHUnozv5kWBAn7aaICMeI?si=dc5bbbfbd4ed4aec',
    },
    {
        name: 'Change',
        artist: 'Fidlar',
        album: 'Surviving The Dream',
        uri: 'https://open.spotify.com/intl-de/track/3jI8usOh9JZiPt3aXjNhWl?si=7a520e01700c488d',
    },
    {
        name: 'Change',
        artist: 'The War On Drugs',
        album: 'I Dont Live Here Anymore',
        uri: 'https://open.spotify.com/intl-de/track/3EPSnqfDkva43w9NdrfFmU?si=bf36e6210f564b90',
    },
    {
        name: 'Change',
        artist: 'White Lies',
        album: 'Big TV',
        uri: 'https://open.spotify.com/intl-de/track/79rd9ZWeh1WKOFmo6J6TXz?si=2fa79c7aca7d4130',
    },
    {
        name: 'Change Your Mind',
        artist: 'The Horrors',
        album: 'Luminous',
        uri: 'https://open.spotify.com/intl-de/track/6TUEvQCUwvBYUuoQp17nwu?si=2b6e32bc839b4856',
    },
    {
        name: 'Change Your Mind',
        artist: 'The Killers',
        album: 'Sawdust',
        uri: 'https://open.spotify.com/intl-de/track/2N7TN76tLuTcdn9UlS8ADT?si=e07998691ff549f6',
    },
    {
        name: 'Change Yr Mind',
        artist: 'LCD Soundsystem',
        album: 'American Dream',
        uri: 'https://open.spotify.com/intl-de/track/0My2pMmVxevwrGyd1CR8u2?si=cff620dba53f46dd',
    },
    {
        name: 'Changes',
        artist: 'Balthazar',
        album: 'Fever',
        uri: 'https://open.spotify.com/intl-de/track/1kG6r8UcvaByJL5kIWPtL9?si=05e0e9c22bcb4272',
    },
    {
        name: 'Changes',
        artist: 'David Bowie',
        album: 'Rolling Stone',
        uri: 'https://open.spotify.com/intl-de/track/0LrwgdLsFaWh9VXIjBRe8t?si=56735ee87c2c4ab4',
    },
    {
        name: 'Changes',
        artist: 'Soccer Mommy',
        album: 'Evergreen',
        uri: 'https://open.spotify.com/intl-de/track/01DJUZDxNB4s4hjGAMwto8?si=eac13eded4174a4a',
    },
]